### ISSUE TITLE
get your shit together

### ISSUE THREAD

**Issue by jamiebuilds** [ejcx/nprlite#1]
<img width="170" alt="screen shot 2017-12-03 at 5 31 16 pm" src="https://user-images.githubusercontent.com/952783/33523013-d7c99300-d84f-11e7-8fdb-04d829bc691c.png">

**Comment by fouad** [comment]
+1

**Comment by ejcx** [comment]
Being an open-source maintainer is hard. You guys just wouldn't understand.

Fixed
